### ISSUE TITLE
change __init__ to take tables instead of `ts` 

### ISSUE THREAD

**Issue by petrelharp** [ashander/ftprime#39]
and set the defaults to be empty

**Comment by petrelharp** [comment]
This would be a little messy, as if this is not specified people still need to say what the initial set of possible individuals is.  What do you think, @ashander, @molpopgen?

**Comment by molpopgen** [comment]
I'm still thinking about this one.  I literally never considered starting with a genealogy.  For my applications, it is not necessary--one doesn't need a MRCA at all sites in order to drop mutations.  And the initial set of possible individuals is something that I just create in table format--basically [0,2N-1] at time 0.
